### ISSUE TITLE
[FEATURE] 글자 가리기 - 도형 기본 UI & 기능 구현

### ISSUE THREAD

**Issue by MeganMagic** [MeganMagic/image-service#3]
# Todo list
- [x] color picker 추가 or palette 추가
- [x] 공통 - bottom sheet 추가
- [x] 색상 바텀시트 오픈 버튼 수정
- [x] userflow: 도형 버튼 클릭 > 도형 선택 > 현재 색상에 맞는 도형 추가

# Future plan
- [ ] editor: 생성된 도형 위치 변경
- [ ] editor: 생성된 도형 색상 변경
- [ ] editor: 생성된 도형 삭제
- [ ] editor: 이미지 영역 스포이드
