### ISSUE TITLE
[Feature] image editor 레포지토리 통합, 도형 관련 추가 기능 개발

### ISSUE THREAD

**Issue by MeganMagic** [MeganMagic/image-service#6]
# Todo
- [x] image editor git submodule 제거
  - 이슈 및 버전 관리 혼동, 그냥 통합하고 labeling 열심히 하기
- [ ] 도형 삭제, 도형 색상 변경 기능 개발
- [x] 도형 선택 시 드로잉 비활성화

# User Flow
- 사용자는 도형을 추가할 수 있다.
- 사용자는 도형을 선택하고 이동하고, 색상을 변경하고, 삭제할 수 있다.
  - 도형과 관련된 동작을 수행하는 중 화면에 그리기가 적용되지 않는다.
- 사용자는 선택한 도형을 해제 할 수 있다.
